remote_theme: hydecorp/hydejack@v9.1.6

lang: en-US
url: https://hamstercheese7.github.io
accent_image: /assets/images/trees.jpg
accent_color: "#136466"
logo: /assets/images/bread.png

title: Ham Town
description: Fanfiction Author, Game Writer, and Zine Enthusiast. Lover of One Piece, Dragon Age, Mass Effect, and too many books to count.

author:
  name: Hamstercheese7
  email: hamstercheese77@gmail.com
  picture: /assets/images/bread.png
  bio: Fanfiction Author, Game Writer, and Zine Enthusiast. Lover of One Piece, Dragon Age, Mass Effect, and too many books to count.
  social:
    twitter: buggyisbest

menu:
  - title: About Ham
    url: /
  - title: Projects
    url: /projects/
  - title: Archive Of Our Own
    url: https://archiveofourown.org/users/hamstercheese7


plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-avatar