remote_theme: hydecorp/hydejack@v9.1.6

lang: en-US
url: https://hamstercheese7.github.io
accent_image: /assets/images/bread.png
accent_color: "#136466"

author:
  name: Hamstercheese7
  email: hamstercheese77@gmail.com
  picture: /assets/images/bread.png
  bio: Fanfiction Author, Game Writer, and Zine Enthusiast. Lover of One Piece, Dragon Age, Mass Effect, and too many books to count.
  social:
    twitter: buggyisbest

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache